# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
    paths:
      - 'Application/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'Application/**'

permissions:
  id-token: write
  contents: read

env:
  registryName: c36swda46dmyywthreg.azurecr.io
  repositoryName: wth/dotnetcoreapp
  dockerFolderPath: Application/src/RazorPagesTestSample
  tag: ${{github.run_number}}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ./Application/src/RazorPagesTestSample/
    - name: Build
      run: dotnet build ./Application/src/RazorPagesTestSample/ --no-restore
    - name: Test
      run: dotnet test ./Application/tests/RazorPagesTestSample.Tests/RazorPagesTestSample.Tests.csproj --no-build --verbosity normal
    
  push:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Docker Login
      run: docker login ${{env.registryName}} -u ${{secrets.ACR_USERNAME }} -p ${{secrets.ACR_PASSWORD}}
    - name: Docker Build
      run: docker build -t $registryName/$repositoryName:$tag --build-arg build_version=$tag $dockerFolderPath
    - name: Docker Push
      run: docker push $registryName/$repositoryName:$tag

  dev:
    needs: [build, push]
    runs-on: ubuntu-latest
    steps:

    - name: Azure login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'c36swda46dmyy-dev'
        images: 'c36swda46dmyywthreg.azurecr.io/wth/dotnetcoreapp:${{env.tag}}'

  test:
    environment: test
    needs: dev
    runs-on: ubuntu-latest
    steps:

    - name: Azure login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'c36swda46dmyy-test'
        images: 'c36swda46dmyywthreg.azurecr.io/wth/dotnetcoreapp:${{env.tag}}'

  prod:
    environment: test
    needs: test
    runs-on: ubuntu-latest
    steps:

    - name: Azure login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'c36swda46dmyy-prod'
        images: 'c36swda46dmyywthreg.azurecr.io/wth/dotnetcoreapp:${{env.tag}}'
    
