# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - 'Application/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'Application/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore Application/src/RazorPagesTestSample/RazorPagesTestSample.csproj
    - name: Build
      run: dotnet build --no-restore Application/src/RazorPagesTestSample/RazorPagesTestSample.csproj
    - name: Test
      run: dotnet test --no-build --verbosity normal Application/tests/RazorPagesTestSample.Tests/RazorPagesTestSample.Tests.cspro
    - name: create issue
      uses: JasonEtco/create-an-issue@v2
      if: failure() # OR Check a bool variable you create and toggle as needed
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: create-issue  
    - run: 'echo Created issue number ${{ steps.create-issue.outputs.number }}'
    - run: 'echo Created ${{ steps.create-issue.outputs.url }}' 