on: 
  workflow_dispatch:
  issues:
    types: [opened]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: Step1
      run : echo "Step1" 
    - name: Step2
      run: echo "Step2"

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Cowsay Action
      uses: mscoutermarsh/cowsays-action@master
      with:
        text: "Hello, from GitHub Actions!"
        color: "purple"