name: ci
on: workflow_dispatch
jobs:
  job1:
    # if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "step1"
      
      - run: echo "step2"

  job2:
    run-on: ubuntu-latest
    steps:
      - name: Ship it
        uses: mscoutermarsh/cowsays-action@master
        with:
          text: 'ship ship ship!'
          color: 'red'