on: workflow_dispatch

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: Step1
      run : echo "Step1" 
    - name: Step2
      run: echo "Step2"

  job2:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Cowsay Action
      uses: nwtgck/gh-action-cowsay@v1
      with:
        text: "Hello, from GitHub Actions!"
    
