on: workflow_dispatch

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: Step1
      run : echo "Step1" 
    - name: Step2
      run: echo "Step2"


  job2:
    runs-on: ubuntu-latest
    steps:
    - name: Step1
      run : echo "Step1" 
    - name: Step2
      run: echo "Step2"
    
